// 数据元类型
const DATA_EL_TYPES = [
  { dataValueTypeName: '文本框', dataValueType: '1' },
  { dataValueTypeName: '单选下拉', dataValueType: '2' },
  { dataValueTypeName: '多选下拉', dataValueType: '3' },
  { dataValueTypeName: '日期', dataValueType: '4' },
  { dataValueTypeName: '数值框', dataValueType: '5' },
  { dataValueTypeName: '勾选框', dataValueType: '6' },
  { dataValueTypeName: '复选框', dataValueType: '7' },
  { dataValueTypeName: '诊断', dataValueType: '8' },
  { dataValueTypeName: '用户签名', dataValueType: '9' },
  { dataValueTypeName: '图片', dataValueType: '14' }
]

const DATA_EL_FORM_ITEM_TYPE_MAP = {
  1: 'input',
  2: 'select',
  3: 'select',
  4: 'datePicker',
  5: 'input',
  6: 'radio',
  7: 'checkbox',
  8: 'text',
  9: 'text',
  14: 'text'
}

const TEST_DATA_ELS = [
  {
    mrasEleDataId: '399582161',
    mrasEleSysClassId: '0',
    conceptId: '399582161',
    dataWinId: 'DHDE063.5706.00',
    dataElementUid: 'DHDE063.5706.00',
    mrasEleDataName: '输血科签字日期',
    dataValueTypeName: '日期',
    dataValueType: '4',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '输血科签字日期',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582160',
    mrasEleSysClassId: '0',
    conceptId: '399582160',
    dataWinId: 'DHDE063.5705.00',
    dataElementUid: 'DHDE063.5705.00',
    mrasEleDataName: '副院长签字日期',
    dataValueTypeName: '日期',
    dataValueType: '4',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '副院长签字日期',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582159',
    mrasEleSysClassId: '0',
    conceptId: '399582159',
    dataWinId: 'DHDE063.5704.00',
    dataElementUid: 'DHDE063.5704.00',
    mrasEleDataName: '医务科签字日期',
    dataValueTypeName: '日期',
    dataValueType: '4',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '医务科签字日期',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582158',
    mrasEleSysClassId: '0',
    conceptId: '399582158',
    dataWinId: 'DHDE063.5703.00',
    dataElementUid: 'DHDE063.5703.00',
    mrasEleDataName: '科主任签字日期',
    dataValueTypeName: '日期',
    dataValueType: '4',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '科主任签字日期',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582027',
    mrasEleSysClassId: '0',
    conceptId: '399582027',
    dataWinId: 'DHDE063.5702.00',
    dataElementUid: 'DHDE063.5702.00',
    mrasEleDataName: '输血科审批意见',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '输血科审批意见',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582026',
    mrasEleSysClassId: '0',
    conceptId: '399582026',
    dataWinId: 'DHDE063.5701.00',
    dataElementUid: 'DHDE063.5701.00',
    mrasEleDataName: '副院长审批意见',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '副院长审批意见',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582025',
    mrasEleSysClassId: '0',
    conceptId: '399582025',
    dataWinId: 'DHDE063.5700.00',
    dataElementUid: 'DHDE063.5700.00',
    mrasEleDataName: '医务科审批意见',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '医务科审批意见',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582024',
    mrasEleSysClassId: '0',
    conceptId: '399582024',
    dataWinId: 'DHDE063.5699.00',
    dataElementUid: 'DHDE063.5699.00',
    mrasEleDataName: '科主任审批意见',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '科主任审批意见',
    imagePath: '',
    dataWinClass: '',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582023',
    mrasEleSysClassId: '0',
    conceptId: '399582023',
    dataWinId: 'DHDE063.5698.00',
    dataElementUid: 'DHDE063.5698.00',
    mrasEleDataName: '输血科签名',
    dataValueTypeName: '用户签名',
    dataValueType: '9',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '输血科签名',
    imagePath: '',
    dataWinClass: '单元信息',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582022',
    mrasEleSysClassId: '0',
    conceptId: '399582022',
    dataWinId: 'DHDE063.5697.00',
    dataElementUid: 'DHDE063.5697.00',
    mrasEleDataName: '副院长签名',
    dataValueTypeName: '用户签名',
    dataValueType: '9',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '副院长签名',
    imagePath: '',
    dataWinClass: '单元信息',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399582021',
    mrasEleSysClassId: '0',
    conceptId: '399582021',
    dataWinId: 'DHDE063.5696.00',
    dataElementUid: 'DHDE063.5696.00',
    mrasEleDataName: '医务科签名',
    dataValueTypeName: '用户签名',
    dataValueType: '9',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '医务科签名',
    imagePath: '',
    dataWinClass: '单元信息',
    hospitalSOID: '10',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: null,
    businessCode: '11',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399542295',
    mrasEleSysClassId: '0',
    conceptId: '399542293',
    dataWinId: 'WIN1.399308810.399542295',
    dataElementUid: 'DHDE076.8649.00',
    mrasEleDataName: '上级医师签名',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '399308810',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '上级医师签名',
    imagePath: '',
    dataWinClass: '病历模板信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: null,
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '0',
    businessCode: '9',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399461130',
    mrasEleSysClassId: '0',
    conceptId: '399444091',
    dataWinId: 'WIN1.399308810.399461130',
    dataElementUid: 'DHDE076.8376.00',
    mrasEleDataName: '时间段代码',
    dataValueTypeName: '单选下拉',
    dataValueType: '2',
    enabledFlag: '98360',
    mrasEleBizClassId: '399308810',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '时间段代码',
    imagePath: '',
    dataWinClass: '病历模板信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: null,
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '375490',
    businessCode: '8',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399459590',
    mrasEleSysClassId: '0',
    conceptId: '399444275',
    dataWinId: 'WIN1.399308810.399459590',
    dataElementUid: 'DHDE076.6856.00',
    mrasEleDataName: '胎儿状态代码',
    dataValueTypeName: '单选下拉',
    dataValueType: '2',
    enabledFlag: '98360',
    mrasEleBizClassId: '399308810',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '胎儿状态代码',
    imagePath: '',
    dataWinClass: '病历模板信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: null,
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '399454668',
    businessCode: '7',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399392601',
    mrasEleSysClassId: '0',
    conceptId: '399392629',
    dataWinId: 'WIN1.347724.399392601',
    dataElementUid: 'DHDE005.1482.00',
    mrasEleDataName: '术中诊断名称',
    dataValueTypeName: '诊断',
    dataValueType: '8',
    enabledFlag: '98360',
    mrasEleBizClassId: '347724',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '术中诊断名称',
    imagePath: '',
    dataWinClass: '诊疗信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: '标准概念',
    dataElementLength: 10,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '0',
    businessCode: '10',
    bindCtrlNo: '991327',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399392600',
    mrasEleSysClassId: '0',
    conceptId: '399392630',
    dataWinId: 'WIN1.347724.399392600',
    dataElementUid: 'DHDE005.1481.00',
    mrasEleDataName: '目前诊断',
    dataValueTypeName: '诊断',
    dataValueType: '8',
    enabledFlag: '98360',
    mrasEleBizClassId: '347724',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '目前诊断',
    imagePath: '',
    dataWinClass: '诊疗信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '0',
    businessCode: '10',
    bindCtrlNo: '991330',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399392599',
    mrasEleSysClassId: '0',
    conceptId: '399392632',
    dataWinId: 'WIN1.347724.399392599',
    dataElementUid: 'DHDE005.1480.00',
    mrasEleDataName: '中医出院诊断名称',
    dataValueTypeName: '诊断',
    dataValueType: '8',
    enabledFlag: '98360',
    mrasEleBizClassId: '347724',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '中医出院诊断名称',
    imagePath: '',
    dataWinClass: '诊疗信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '0',
    businessCode: '10',
    bindCtrlNo: '256919',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399392598',
    mrasEleSysClassId: '0',
    conceptId: '399392631',
    dataWinId: 'WIN1.347724.399392598',
    dataElementUid: 'DHDE005.1479.00',
    mrasEleDataName: '中医入院诊断名称',
    dataValueTypeName: '诊断',
    dataValueType: '8',
    enabledFlag: '98360',
    mrasEleBizClassId: '347724',
    deDisplayedName: null,
    numericMin: null,
    dataElementDesc: '中医入院诊断名称',
    imagePath: '',
    dataWinClass: '诊疗信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: null,
    conceptDomainId: '0',
    businessCode: '10',
    bindCtrlNo: '256918',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399337994',
    mrasEleSysClassId: '0',
    conceptId: '399337994',
    dataWinId: 'DHDE001.0215.00',
    dataElementUid: 'DHDE001.0215.00',
    mrasEleDataName: '职称代码',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '',
    numericMin: '',
    dataElementDesc: '职称代码',
    imagePath: '',
    dataWinClass: '社会学信息',
    hospitalSOID: '993718',
    numericMax: '',
    dataWinType: '标准概念',
    dataElementLength: 0,
    deNumericFormat: '',
    datetimeFormat: '',
    numericDigit: 11,
    conceptDomainId: '65047',
    businessCode: '2',
    bindCtrlNo: '',
    controlAttrs: null,
    valueAttrs: null
  },
  {
    mrasEleDataId: '399337751',
    mrasEleSysClassId: '0',
    conceptId: '399337751',
    dataWinId: 'WIN1.347731.98260',
    dataElementUid: 'DHDE012.0043.00',
    mrasEleDataName: '申请用血量',
    dataValueTypeName: '文本框',
    dataValueType: '1',
    enabledFlag: '98360',
    mrasEleBizClassId: '347720',
    deDisplayedName: '申请用血量',
    numericMin: null,
    dataElementDesc: '申请用血量',
    imagePath: null,
    dataWinClass: '输血信息',
    hospitalSOID: '10',
    numericMax: null,
    dataWinType: '标准概念',
    dataElementLength: null,
    deNumericFormat: null,
    datetimeFormat: null,
    numericDigit: 11,
    conceptDomainId: '0',
    businessCode: '5',
    bindCtrlNo: '1',
    controlAttrs: null,
    valueAttrs: null
  }
]

export {
  DATA_EL_TYPES,
  DATA_EL_FORM_ITEM_TYPE_MAP,
  TEST_DATA_ELS
}
